name: Build and Release Arduino Project

on:
  push:
    tags:
      - "v*.*.*" # Triggers the workflow on version tags
  workflow_dispatch: # Allows the workflow to be run on demand

permissions:
  contents: write # Grants write permissions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Arduino CLI
        run: |
          mkdir -p ~/arduino-cli
          cd ~/arduino-cli
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh

      - name: Install ESP32 core
        run: |
          ~/arduino-cli/bin/arduino-cli core update-index
          ~/arduino-cli/bin/arduino-cli core install esp32:esp32

      - name: Install dependencies
        run: |
          ~/arduino-cli/bin/arduino-cli lib install ArduinoJson
          ~/arduino-cli/bin/arduino-cli lib install HTTPClient

      - name: Compile sketch
        run: |
          mkdir -p ./binaries
          ~/arduino-cli/bin/arduino-cli compile --fqbn esp32:esp32:esp32s2 --libraries ./libraries --output-dir ./binaries ./flipper-postman-esp32s2.ino

      - name: Create Release
        uses: softprops/action-gh-release@v2

        with:
          files: binaries/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            This is the release for version ${{ github.ref }}.
            It contains the compiled binaries for the ESP32-S2 Flipper Dev Board.
